server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autopart
    username: dev_user
    password: w0a5nhnu4
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: autopartservice2023@gmail.com
    password: cwfbmuplchlcbwot
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true
  #image
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

logging:
  file:
    name: log/autopart.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]' : WARN
    '[org.hibernate]' : INFO
    '[org.autopart]' : DEBUG

management: #actuator
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

autopart:
  app:
    jwtSecret: autoPart#!June2023
    jwtExpirationMs: 86400000
    backendLink: http://localhost:8080/

info:
  application:
    name: 'Auto Part E-Commerce Backend Application'
    description: 'This is Auto Part E-Commerce Backend Project'
    version: '@project.version@'

